[package]
name = 'example'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/davidiw/aptos-core.git'
rev = 'conversions'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.ZeeOracle]
git = 'https://github.com/ZeeFi/zee-oracle.git'
rev = 'main'
subdir = 'move'




[addresses]
AptosFramework="0x1"
zee_oracle="0xda9724a10e323b710f08087951e88b9b2818196f0159a111beb5a394d969416c"
example= "0xb42175fd5ce66ec91aa52942199f63766f1a90e62fb3bd5f455413fb8f4a75a5"